Token caching and validation
thoughtspot/visual-embed-sdk pull request #1023
Opened 2023-11-20 18:09 UTC by sastaachar

2023-11-20 19:55 UTC, ashubham requested changes

2023-11-20 19:55 UTC, ashubham commented on src/authToken.ts
> +            throw new Error(DUPLICATE_TOKEN_ERR);
what the point of throwing errors here, if we are anyways catch it in the same block.

2023-11-20 19:55 UTC, ashubham commented on src/utils/graphql/answerService/answerService.ts
> +        return tokenizedFetch(fetchUrl, {
Are there other places we need to use tokenizedFetch ?

2023-11-20 19:55 UTC, ashubham commented on src/tokenizedFetch.ts
> +    const authToken = await getAuthenticationToken(embedConfig);
What if the user is not using TrustedAuthCookieless ?

2023-11-21 03:32 UTC, sastaachar commented on src/utils/graphql/answerService/answerService.ts
> +        return tokenizedFetch(fetchUrl, {
yes , execute and import TML , 

cc: @adityamittal3107 @Nirmay15  please do suggest if we need this anywhere else

2023-11-30 08:29 UTC, abdullasulaiman requested changes

2023-11-30 08:29 UTC, abdullasulaiman commented on src/auth.ts
> +        if (authToken) return true;
let isAuthenticated = false;
if (authToken) { isAuthenticated = true };

2023-11-30 08:29 UTC, abdullasulaiman commented on src/authToken.ts
> +            // Continue to get a new token if validation fails
Look at this block to make for debugging purpose.

2023-11-30 10:19 UTC, abdullasulaiman approved these changes
LGTM

2023-12-05 07:42 UTC, ashubham approved these changes

2023-12-05 07:52 UTC, merged