Add reactShellEnabled Config to Visual Embed SDK
thoughtspot/visual-embed-sdk pull request #1035
Opened 2023-12-11 20:16 UTC by utsavkapoor

2023-12-11 22:31 UTC, ashubham requested changes

2023-12-11 22:31 UTC, ashubham commented on src/types.ts
> +    enableReactShell?: boolean | undefined;
lets call this `enableV2Shell` ?

2023-12-11 22:31 UTC, ashubham commented on src/embed/ts-embed.ts
> +    protected getRootIframeSrc(enableReactShell : boolean|undefined): string {
Why does this need to be passed from all embed types ? We can just read the config inside this method and add the appropriate flag.

2023-12-11 22:31 UTC, ashubham commented on src/types.ts
> +    enableReactShell?: boolean | undefined;
Also, does this need to be on ViewConfig ? I feel we should add this to EmbedConfig so that it can be added when the developer calls `init` for once within the SDK.

2023-12-11 23:44 UTC, utsavkapoor commented on src/types.ts
> +    enableReactShell?: boolean | undefined;
done.

2023-12-11 23:45 UTC, utsavkapoor commented on src/embed/ts-embed.ts
> +    protected getRootIframeSrc(enableReactShell : boolean|undefined): string {
done

2023-12-12 22:48 UTC, ashubham approved these changes

2023-12-12 22:48 UTC, ashubham commented on src/types.ts
> +    HideSageAnswerHeader = 'hideSageAnswerHeader'
do not remove trailing comma

2023-12-12 22:48 UTC, ashubham commented on src/types.ts
> +     * If true, all the iframe links will have /v2 added automatically.
This comment should make sense to an external (non-thoughtspot) developer.

2023-12-13 00:28 UTC, merged