SCAL-188111 : Console log control
thoughtspot/visual-embed-sdk pull request #1040
Opened 2024-01-30 06:06 UTC by sastaachar

2024-02-06 05:27 UTC, pushkar100 requested changes

2024-02-06 05:27 UTC, pushkar100 commented on src/utils/logger.ts
> +};
nit `logLevels`

Why can we not have enums for this?

2024-02-06 05:27 UTC, pushkar100 commented on src/utils/logger.ts
> +};
```suggestion
const compareLogLevels = (logLevel1: LogLevel, logLevel2: LogLevel): number => logLevelToNumber[logLevel1] - logLevelToNumber[logLevel2];
```

2024-02-06 05:27 UTC, pushkar100 commented on src/utils/logger.spec.ts
> +        const a = await import('./logger');
Why do we need a dynamic import here?

2024-02-06 05:27 UTC, pushkar100 commented on src/utils/logger.spec.ts
> +        expect(logger.getLogLevel()).toBe(LogLevel.DEBUG);
Add assertions for all the levels

2024-02-06 05:27 UTC, pushkar100 commented on src/utils/logger.spec.ts
> +        logger.setLogLevel(LogLevel.ERROR);
Should add similar assertions for trace, info, debug... as well

2024-02-06 05:27 UTC, pushkar100 commented on src/utils/logger.ts
> +};
https://www.typescriptlang.org/docs/handbook/enums.html
([Example](https://www.typescriptlang.org/play?#code/KYOwrgtgBAIglgJ2AYwC5wPYigbwFBRQCqADlALxQCMANAbBgO4h2EAywAZqq1AEpwA5gAseeAL548yLAGcMAG2AA6BRkEAKeEjSYQy0lAC0sRCnRZlMJiACUQA))

2024-02-06 05:27 UTC, pushkar100 commented on src/types.ts
> +}
We can have number based enums here and get rid of `logLevelToNumber`

2024-02-06 05:27 UTC, pushkar100 commented on src/utils/logger.ts
> +        return compareLogLevels(this.logLevel, logLevel) >= 0;
Looks like `globalLogLevelOverride` is always set in base.ts. Will Line 49 ever execute in the embed sdk?

2024-02-08 05:41 UTC, sastaachar commented on src/types.ts
> +}
blink takes it as string , hence this also this helps with customers who use direct iframe as reference 
so wanted to keep this simple

2024-02-08 05:41 UTC, sastaachar commented on src/utils/logger.ts
> +        return compareLogLevels(this.logLevel, logLevel) >= 0;
not yet , but will need when we have multiple orgs

2024-02-08 06:00 UTC, sastaachar commented on src/utils/logger.ts
> +};
mainly because we dont have to maintain the names in two diff place 
clear readability 
maintaining value for LogLevel at single place

2024-02-08 06:01 UTC, sastaachar commented on src/utils/logger.spec.ts
> +        const a = await import('./logger');
cause ./logger sets the log values when imported 
so we should mock the consoles before importing it

2024-02-09 04:32 UTC, pushkar100 approved these changes
LGTM

2024-02-16 06:26 UTC, merged