SCAL-79910-subfolder-in-build-for-deployment
thoughtspot/visual-embed-sdk pull request #105
Opened 2021-03-19 06:41 UTC by pankajp-ts

Ticket - https://thoughtspot.atlassian.net/browse/SCAL-79910

2021-03-19 08:33 UTC, ashubham commented on docs/src/configs/doc-configs.js
> +    DOC_REPO_NAME: '/visual-embed-sdk/dev',
Will hardcoding this not break /release path ?

2021-03-23 05:41 UTC, ashubham commented on .github/workflows/deploy.yml
> +      - release
Instead of automatically publishing on `release` branch push. We should have a manual trigger which will publish the `release` version of the docs.

2021-03-23 05:42 UTC, ashubham commented on gatsby-config.js
> +            return '';
Please put a comment for the use case of empty string. (For local development).

2021-03-23 05:43 UTC, ashubham submitted a review, later dismissed
Please make the commented changes

2021-03-23 12:20 UTC, jbhanu-thoughtspot requested changes

2021-03-23 12:20 UTC, jbhanu-thoughtspot commented on .github/workflows/deploy.yml
> +  workflow_dispatch:
Ending with a colon(`:`) seems to indicate more continuation script in the following. Would this work as expected when we run for release?

2021-03-23 12:20 UTC, jbhanu-thoughtspot commented on gatsby-config.js
> +            return '';
remove this `return` and both cases `'LOCAL'` and `default` can return the same value.

2021-03-23 12:48 UTC, sumit-thoughtspot commented on .github/workflows/deploy.yml
> +  workflow_dispatch:
I wasn't able to test it. But it should work as expected.

2021-03-23 14:06 UTC, jbhanu-thoughtspot approved these changes
lgtm

2021-03-23 14:08 UTC, merged