[SCAL-215364] Add config to enable data panel v2 when only liveboard is embedded
thoughtspot/visual-embed-sdk pull request #1175
Opened 2024-07-26 10:40 UTC by bishalts2019

2024-08-21 18:35 UTC, utsavkapoor requested changes

2024-08-21 18:35 UTC, utsavkapoor commented on src/types.ts
> +     * @version SDK: 1.26.0 | Thoughtspot: 9.7.0.cl
Fix the SDK Version and Thoughtspot version

2024-08-21 18:35 UTC, utsavkapoor commented on src/embed/liveboard.spec.ts
> +                `http://${thoughtSpotHost}/?embedApp=true${defaultParams}${prefixParams}&enableDataPanelV2=true#/embed/viz/${liveboardId}`,
Lets not do this. Can you add a new UT for this ?

2024-08-22 09:23 UTC, bishalts2019 commented on src/embed/liveboard.spec.ts
> +                `http://${thoughtSpotHost}/?embedApp=true${defaultParams}${prefixParams}&enableDataPanelV2=true#/embed/viz/${liveboardId}`,
sure

2024-08-22 09:24 UTC, bishalts2019 commented on src/types.ts
> +     * @version SDK: 1.26.0 | Thoughtspot: 9.7.0.cl
done

2024-08-22 20:07 UTC, utsavkapoor approved these changes

2024-08-26 06:09 UTC, merged