SCAL-81508-logo-and-footer-for-public-site
thoughtspot/visual-embed-sdk pull request #142
Opened 2021-03-31 13:29 UTC by pankajp-ts

Ticket - https://thoughtspot.atlassian.net/browse/SCAL-81508

2021-04-01 02:14 UTC, ashubham submitted a review, later dismissed

2021-04-01 02:14 UTC, ashubham commented on docs/src/components/Footer/index.tsx
> +                <span>©2021 ThoughtSpot Inc. All Rights Reserved.</span>
do we have a strings file ?

2021-04-01 02:14 UTC, ashubham commented on docs/src/utils/app-utils.ts
> +    queryParamObj[IS_PUBLIC_SITE_OPEN] = isPublicSiteOpen;
Why are we putting this in queryParam ? This is not coming from query string in the url

2021-04-01 02:15 UTC, ashubham commented on docs/src/components/Footer/index.tsx
> +    <footer>
Is this approved by design ?

2021-04-01 03:59 UTC, pankajp-ts commented on docs/src/components/Footer/index.tsx
> +    <footer>
I asked for designs but we don't have it as of now. Header is based on earlier design, footer is new.

2021-04-01 04:02 UTC, pankajp-ts commented on docs/src/utils/app-utils.ts
> +    queryParamObj[IS_PUBLIC_SITE_OPEN] = isPublicSiteOpen;
Actually this we are extracting by checking query params, that's why we put it there.

2021-04-01 05:23 UTC, pankajp-ts commented on docs/src/components/Footer/index.tsx
> +                <span>©2021 ThoughtSpot Inc. All Rights Reserved.</span>
Yes we have. Added all strings from all files.

2021-04-01 06:10 UTC, ashubham commented on docs/src/components/Footer/index.tsx
> +    <footer>
Lets post this on the TSE channel to get feedback

2021-04-01 06:11 UTC, ashubham commented on docs/src/utils/app-utils.ts
> +    queryParamObj[IS_PUBLIC_SITE_OPEN] = isPublicSiteOpen;
But I dont think this should be here, maybe export another util method to check if its a public site ?

2021-04-01 07:03 UTC, pankajp-ts commented on docs/src/utils/app-utils.ts
> +    queryParamObj[IS_PUBLIC_SITE_OPEN] = isPublicSiteOpen;
done

2021-04-01 09:03 UTC, ShashiSubramanya reviewed
Header looks good. 
You may want to revisit the footer design.

2021-04-07 07:17 UTC, harsh-ts commented
@ashubham and @ShashiSubramanya please check new footer style

Desktop

![image](https://user-images.githubusercontent.com/78337774/113825609-d0e18680-979e-11eb-8bba-0c4b9fcf4a06.png)

Mobile

![image](https://user-images.githubusercontent.com/78337774/113826007-4a797480-979f-11eb-8c40-d6b2be974aa7.png)

2021-04-09 05:13 UTC, jbhanu-thoughtspot requested changes

2021-04-09 05:13 UTC, jbhanu-thoughtspot commented on docs/src/utils/app-utils.ts
> +            isPublicSiteOpen = false;
this can be `return false`
Don't have to loop through all the entries.

2021-04-09 05:13 UTC, jbhanu-thoughtspot commented on docs/src/utils/app-utils.ts
> +    return isPublicSiteOpen;
And here `return true`. Don't need to assign to a variable

2021-04-09 05:39 UTC, jbhanu-thoughtspot approved these changes
LGTM

2021-04-09 05:40 UTC, merged