[SCAL-80348] Left nav collapse expand
thoughtspot/visual-embed-sdk pull request #145
Opened 2021-04-05 04:28 UTC by harsh-ts

Ticket Link: https://thoughtspot.atlassian.net/browse/SCAL-80348

2021-04-05 07:42 UTC, pankajp-ts commented
@harsh-ts I observed that whenever we click on nav item it's flickering, can we please check this issue and update the PR.

2021-04-06 17:43 UTC, jbhanu-thoughtspot requested changes

2021-04-06 17:43 UTC, jbhanu-thoughtspot commented on docs/src/components/LeftSidebar/helper.ts
> +            '.navWrapper>.ulist>ul>li>div.ulist',
Can you add these selectors to some const variables to have them identified with a name for readability

2021-04-06 17:43 UTC, jbhanu-thoughtspot commented on docs/src/components/LeftSidebar/helper.ts
> +        if (typeof divElement !== 'undefined') {
Can be a simple check such as `if (!!divElement) {`

2021-04-06 17:43 UTC, jbhanu-thoughtspot commented on docs/src/components/LeftSidebar/helper.ts
> +            if (typeof allLinks !== 'undefined') {
allLinks will never be undefined as querySelectorAll returns an empty array, if the selector is not found.
You can remove this if

2021-04-06 17:43 UTC, jbhanu-thoughtspot commented on docs/src/components/LeftSidebar/helper.ts
> +    setTimeout(() => {
Why do you need the setTimeout here?

2021-04-06 17:43 UTC, jbhanu-thoughtspot commented on docs/src/components/LeftSidebar/helper.ts
> +        document
Can you get the ref of navWrapper and add the eventlistener instead of searching on the document?

2021-04-07 04:41 UTC, harsh-ts commented on docs/src/components/LeftSidebar/helper.ts
> +            '.navWrapper>.ulist>ul>li>div.ulist',
Yeah sure.

2021-04-07 04:41 UTC, harsh-ts commented on docs/src/components/LeftSidebar/helper.ts
> +        if (typeof divElement !== 'undefined') {
Yeah that makes sense. Thanks!

2021-04-07 04:44 UTC, harsh-ts commented on docs/src/components/LeftSidebar/helper.ts
> +            if (typeof allLinks !== 'undefined') {
Yeah sure

2021-04-07 04:44 UTC, harsh-ts commented on docs/src/components/LeftSidebar/helper.ts
> +    setTimeout(() => {
We need to wait for the DOM to be rendered otherwise the click listeners will not be attached to the said elements.

2021-04-07 05:00 UTC, harsh-ts commented on docs/src/components/LeftSidebar/helper.ts
> +        document
Okay sure

2021-04-09 05:37 UTC, jbhanu-thoughtspot requested changes

2021-04-09 05:37 UTC, jbhanu-thoughtspot commented on docs/src/components/LeftSidebar/helper.ts
> +    nav.querySelectorAll('.navWrapper>.ulist>ul>li>p').forEach((tag, index) => {
Can you move all the selectors to constants?
`.navWrapper>.ulist>ul>li>p`

2021-04-09 05:37 UTC, jbhanu-thoughtspot commented on docs/src/components/LeftSidebar/helper.ts
> +const linksContainer = '.navWrapper>.ulist>ul>li>div.ulist';
You can maybe create a selectors object,

```
const selectors = {
    linksContainer: '.navWrapper>.ulist>ul>li>div.ulist'
}
```

And rest of the selectors in this object.

2021-04-09 05:37 UTC, jbhanu-thoughtspot commented on docs/src/components/LeftSidebar/helper.ts
> +    setTimeout(() => {
setTimeout is a race condition, if content takes more time than the 100ms you set, it will fail to work. Can you think of a different approach to check if the dom is rendered?

2021-04-09 05:37 UTC, jbhanu-thoughtspot commented on docs/src/components/LeftSidebar/helper.ts
> +export const collapseAndExpandLeftNav = (ref: React.RefObject<HTMLDivElement>, setLeftNavOpen: Function) => {
Take the element directly, no need to pass the ref here.
`export const collapseAndExpandLeftNav = (navEl: HTMLDivElement, setLeftNavOpen: Function) => {`

2021-04-14 08:11 UTC, harsh-ts commented on docs/src/components/LeftSidebar/helper.ts
> +    nav.querySelectorAll('.navWrapper>.ulist>ul>li>p').forEach((tag, index) => {
Okay sure.

2021-04-14 08:11 UTC, harsh-ts commented on docs/src/components/LeftSidebar/helper.ts
> +const linksContainer = '.navWrapper>.ulist>ul>li>div.ulist';
Yeah that makes sense. Thanks!

2021-04-14 08:12 UTC, harsh-ts commented on docs/src/components/LeftSidebar/helper.ts
> +export const collapseAndExpandLeftNav = (ref: React.RefObject<HTMLDivElement>, setLeftNavOpen: Function) => {
Yeah sure

2021-04-14 08:13 UTC, harsh-ts commented on docs/src/components/LeftSidebar/helper.ts
> +    setTimeout(() => {
I've removed setTimeout and added nav content dependency in useEffect.

2021-04-14 09:02 UTC, harsh-ts commented on docs/src/components/LeftSidebar/helper.ts
> +    setTimeout(() => {
Added navContent in dependency for useEffect

2021-04-14 13:22 UTC, jbhanu-thoughtspot approved these changes
LGTM

2021-04-14 13:22 UTC, merged