WIP: [SCAL-81933, SCAL-73433]
thoughtspot/visual-embed-sdk pull request #154
Opened 2021-04-09 06:02 UTC by sumit-thoughtspot

2021-04-20 04:20 UTC, thrinethra-thoughtspot requested changes
Addressed the comments.

2021-04-21 15:55 UTC, jbhanu-thoughtspot commented on src/auth.ts
>          credentials: 'include',
@thrinethra-thoughtspot isLoggedIn will give sessionInfo only after logging in. So, we need handle the initial flow when it is not yet logged in as well.
1) Basic auth & Token auth: Use the response from the login call for storing sessionInfo.
2) Saml auth: After the login redirection, make a new getSessionInfo (or isLoggedIn) call.

2021-04-22 10:19 UTC, thrinethra-thoughtspot commented on src/auth.ts
>          credentials: 'include',
Resolved by calling initMixpanel in auth.ts init method and making call to fetch mixpanel token.

2021-04-27 05:20 UTC, ashubham approved these changes

2021-04-27 05:20 UTC, ashubham commented on .idea/codeStyles/Project.xml
> +<component name="ProjectCodeStyleConfiguration">
remove these .idea files ?

2021-04-27 06:09 UTC, ashubham approved these changes

2021-04-27 06:09 UTC, ashubham commented on src/mixpanel-service.ts
> +    fetch(`${thoughtSpotHost}${EndPoints.CONFIG}`)
Please return this promise, so if someone wants to wait on this can do so.

2021-04-29 04:12 UTC, merged