Scal 82081 large result set for answer
thoughtspot/visual-embed-sdk pull request #212
Opened 2021-06-11 08:55 UTC by gaurav-thoughtspot

2021-06-16 09:53 UTC, gaurav-thoughtspot commented on src/utils/fetchAnswers.ts
> +            variable = {
> Is this valid in case of all the other operations?

Yes, Because we initializing getAnswerServiceInstance for OperationType: GetChartWithData & GetTableWithHeadlineData only, so else case for GetTableWithHeadlineData only.

2021-06-17 05:16 UTC, jbhanu-thoughtspot requested changes

2021-06-17 05:16 UTC, jbhanu-thoughtspot commented on src/embed/base.ts
> +import AnswerService from '../utils/answerService';
```
import getAnswerServiceInstance from './utils/answerService';
```

2021-06-17 05:16 UTC, jbhanu-thoughtspot commented on src/embed/base.ts
> +            const getAnswerServiceInstance = AnswerService(
```
const answerService = getAnswerServiceInstance()
```

2021-06-17 05:16 UTC, jbhanu-thoughtspot commented on src/embed/base.ts
> +            data.AnswerService = getAnswerServiceInstance;
data.answerService = answerService;

2021-06-17 05:16 UTC, jbhanu-thoughtspot commented on src/utils/answerService.ts
> +function getAnswerServiceInstance(
You can export the method directly to maintain the name.

`export function getAnswerServiceInstance`

2021-06-17 05:16 UTC, jbhanu-thoughtspot commented on src/utils/answerService.ts
> +export default getAnswerServiceInstance;
No need of default export

2021-06-17 05:16 UTC, jbhanu-thoughtspot commented on src/embed/base.ts
> +    private processData(_data: any) {
Let's move this to a separate file. And make use of switch for each of the action types to segregate it better.

example:
```
function processData(event) {
    switch (event.type) {
        case EventType.CustomAction:
            return processCustomAction(event);
    }
    return event;
}

function processCustomAction(event) {
    // custom action process logic
}
```

2021-06-17 12:15 UTC, jbhanu-thoughtspot requested changes

2021-06-17 12:15 UTC, jbhanu-thoughtspot commented on src/types.ts
> +export enum EventType {
There is already an enum for this, you don't need to create another

2021-06-17 12:15 UTC, jbhanu-thoughtspot commented on src/utils/processData.ts
> +        case EventType.CustomAction:
Use the `Action` enum

2021-06-17 12:15 UTC, jbhanu-thoughtspot commented on src/embed/base.ts
> +                this.executeCallbacks(eventType, data);
```
this.executeCallbacks(eventType, processData(event.data, this.thoughtSpotHost));
```

2021-06-17 12:50 UTC, jbhanu-thoughtspot approved these changes
lgtm

2021-06-17 12:55 UTC, merged