- Added reload logic and mixpanel triggers
thoughtspot/visual-embed-sdk pull request #229
Opened 2021-06-23 10:15 UTC by harsh-ts

Ticket Id: https://thoughtspot.atlassian.net/browse/SCAL-86271

2021-06-28 09:01 UTC, jbhanu-thoughtspot requested changes

2021-06-28 09:01 UTC, jbhanu-thoughtspot commented on src/embed/base.ts
> +        if (messageType === HostEvent.Reload) {
Let's move this logic to a different, refer to `src/utils/processData.ts` which is handling the `.on`. Make a similar approach that uses the switch case for different trigger types.

2021-06-29 07:59 UTC, harsh-ts commented on src/embed/base.ts
> +        if (messageType === HostEvent.Reload) {
We are having only 3 cases for trigger event and using switch for only 3 events will be expensive. Let me know your thoughts on this @jbhanu-thoughtspot

2021-07-05 06:28 UTC, jbhanu-thoughtspot commented on src/utils/processTrigger.ts
> +            );
Let's move this part as a separate method as well as we might re-use that in other switch cases at a later point

2021-07-05 06:28 UTC, jbhanu-thoughtspot commented on src/embed/base.ts
> +        if (messageType === HostEvent.Reload) {
We are just starting to add the trigger events and pretty soon we will be having many of them and each having a different type of code flow.

2021-07-05 12:31 UTC, jbhanu-thoughtspot commented on src/utils/processTrigger.ts
> +                { type: messageType, data },
Pass them as messageType and data as how you are receiving in this method, and form the message object inside the postIframeMessage

2021-07-06 04:46 UTC, jbhanu-thoughtspot approved these changes
lgtm

2021-07-06 04:46 UTC, merged