SCAL-86402 Add examples folder
thoughtspot/visual-embed-sdk pull request #249
Opened 2021-07-12 06:19 UTC by aditya-kumar44

Added all 4 sections
* Search
* Pinboard
* Visualisation
* Full App

2021-07-15 17:17 UTC, ashubham commented
I think this going directly going into the top level is confusing. Can we create an `examples/app-with-custom-actions` subdirectory ? That way we can have more specific examples also in the same directory.

2021-07-19 04:28 UTC, jbhanu-thoughtspot requested changes

2021-07-19 04:28 UTC, jbhanu-thoughtspot commented on examples/src/components/feedback-analysis/FeedbackAnalysis.tsx
> +} from "@thoughtspot/visual-embed-sdk";
This is the part we need to use from the code, instead of taking from npm modules

2021-07-19 04:28 UTC, jbhanu-thoughtspot commented on examples/src/components/fullApp/FullApp.tsx
> +import {
Update similar to previous comments

2021-07-19 04:28 UTC, jbhanu-thoughtspot commented on examples/src/components/feedback-analysis/FeedbackAnalysis.tsx
> +import React from "react";
Can you rename this file, to one of our options? This is an examples folder, not Clover bank, so we don't need to maintain the same naming

2021-07-19 04:28 UTC, jbhanu-thoughtspot commented on examples/src/components/send-survey-modal/SendSurveyModal.tsx
> +import React from 'react';
We don't need this

2021-07-19 04:28 UTC, jbhanu-thoughtspot commented on examples/src/services/survey/survey-service.ts
> +const SURVEYMONKEY_TOKEN =
we don't need this

2021-07-19 04:28 UTC, jbhanu-thoughtspot commented on examples/src/reportWebVitals.ts
> +import { ReportHandler } from 'web-vitals';
we don't need this

2021-07-19 04:28 UTC, jbhanu-thoughtspot commented on examples/src/setupTests.ts
> +import '@testing-library/jest-dom';
we don't need the test setup

2021-07-19 04:28 UTC, jbhanu-thoughtspot commented on examples/fakedata/fake-ts-custom-action-payload.json
> +{
not needed

2021-07-19 04:28 UTC, jbhanu-thoughtspot commented on examples/src/logo.svg
> +<svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 841.9 595.3"><g fill="#61DAFB"><path d="M666.3 296.5c0-32.5-40.7-63.3-103.1-82.4 14.4-63.6 8-114.2-20.2-130.4-6.5-3.8-14.1-5.6-22.4-5.6v22.3c4.6 0
Do we need this image?
Can you check and remove all the other resources that are not needed in this example folders?
eg: `examples/ec2-user@10.85.78.52`, `examples/src/assets/Chart_01.png`

2021-07-25 03:34 UTC, aditya-kumar44 commented on examples/LICENSE
> +MIT License
Done

2021-07-25 03:36 UTC, aditya-kumar44 commented on examples/README.md
> +# Getting Started with Create React App
Done

2021-07-25 03:36 UTC, aditya-kumar44 commented on examples/README.old.md
> +# clover-bank
Done

2021-07-25 03:37 UTC, aditya-kumar44 commented on examples/fakedata/fake-ts-custom-action-payload.json
> +{
Done

2021-07-25 03:38 UTC, aditya-kumar44 commented on examples/package.json
> +    "start": "react-scripts start",
DOne

2021-07-25 03:40 UTC, aditya-kumar44 commented on examples/src/App.test.tsx
> +import React from 'react';
Done

2021-08-30 17:23 UTC, aditya-kumar44 commented on examples/src/logo.svg
> +<svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 841.9 595.3"><g fill="#61DAFB"><path d="M666.3 296.5c0-32.5-40.7-63.3-103.1-82.4 14.4-63.6 8-114.2-20.2-130.4-6.5-3.8-14.1-5.6-22.4-5.6v22.3c4.6 0
Done

2021-08-30 17:24 UTC, aditya-kumar44 commented on examples/src/setupTests.ts
> +import '@testing-library/jest-dom';
done

2021-08-30 17:24 UTC, aditya-kumar44 commented on examples/src/reportWebVitals.ts
> +import { ReportHandler } from 'web-vitals';
done

2021-08-30 17:24 UTC, aditya-kumar44 commented on examples/src/services/survey/survey-service.ts
> +const SURVEYMONKEY_TOKEN =
done

2021-08-30 17:28 UTC, aditya-kumar44 commented on examples/.gitignore
> +# See https://help.github.com/articles/ignoring-files/ for more about ignoring files.
Not sure about this. Need guidance

2021-08-30 17:32 UTC, aditya-kumar44 commented on examples/src/components/feedback-analysis/FeedbackAnalysis.tsx
> +  : "https://10.87.90.95";
Done

2021-08-30 17:37 UTC, aditya-kumar44 commented on examples/src/components/feedback-analysis/FeedbackAnalysis.tsx
> +import React from "react";
Done

2021-08-30 17:37 UTC, aditya-kumar44 commented on examples/src/components/feedback-analysis/FeedbackAnalysis.tsx
> +} from "@thoughtspot/visual-embed-sdk";
Need guidance

2021-08-30 17:38 UTC, aditya-kumar44 commented on examples/src/components/fullApp/FullApp.tsx
> +import {
Need Guidance

2021-09-02 21:18 UTC, aditya-kumar44 commented
> I think this going directly going into the top level is confusing. Can we create an `examples/app-with-custom-actions` subdirectory ? That way we can have more specific examples also in the same directory.

Done

2021-09-03 06:13 UTC, jbhanu-thoughtspot approved these changes
lgtm

2021-09-03 06:14 UTC, merged