[SCAL-93058] create prefetch method
thoughtspot/visual-embed-sdk pull request #326
Opened 2021-08-17 15:22 UTC by cristian-cojocaru-ts

2021-08-17 16:30 UTC, akashmohapatra commented on src/embed/base.ts
> +                const prefetchIframe = document.getElementById(
Can there be a scenario wherein there are multiple embeds on the same host page, it will still clean up well?

2021-08-20 13:32 UTC, cristian-cojocaru-ts commented on src/embed/base.ts
> +                const prefetchIframe = document.getElementById(
good point. fixed.

2021-08-25 13:11 UTC, akashmohapatra commented on src/embed/base.ts
> +
We will also need to document what this does. Considering that this is not invoking auth(probably rightly so), there should be some guidance on where and when it can be useful. What do you think @ashubham

2021-08-31 04:15 UTC, ashubham requested changes

2021-08-31 04:15 UTC, ashubham commented on src/embed/base.ts
> +    iFrame.src = config.thoughtSpotHost || url || '';
I agree with @akashmohapatra suggestion here. If an explicit `url` is passed it should be honored. 

Also, if none is available (the '' case). We should perhaps throw a warning saying that no `url` to prefetch.

2021-08-31 04:15 UTC, ashubham commented on src/embed/ts-embed.ts
> +                    '.prefetchIframe',
we should perhaps be using an `id` here to be semantically correct.

2021-08-31 04:15 UTC, ashubham commented on src/index.ts
>      init,
We should also expose a property on `init`. Something like `prefetch: true`, which when set should call the prefetch method internally.

2021-08-31 04:16 UTC, ashubham commented on src/embed/base.spec.ts
> +            expect(prefetchIframe.length).toBe(1);
Can we also check the `src` of the iframe ?

2021-08-31 13:06 UTC, cristian-cojocaru-ts commented on src/embed/ts-embed.ts
> +                    '.prefetchIframe',
technically, they could call prefetch multiple times which would generate multiple iframes, so I used classes to avoid having multiple DOM elements with the same id

2021-09-01 13:46 UTC, akashmohapatra commented on src/embed/base.ts
> +    if (iFrame.src === '') {
Please have the url check for empty string before setting to the iframe src as it can potentially trigger a mixed content alert to the browser in https hosts. If empty, the reset of the steps can be skipped.

2021-09-03 16:51 UTC, akashmohapatra approved these changes

2021-09-06 05:49 UTC, merged