add visibleActions param
thoughtspot/visual-embed-sdk pull request #349
Opened 2021-09-07 14:59 UTC by cristian-cojocaru-ts

2021-09-07 20:31 UTC, ashubham commented on src/embed/search.ts
> +        }
I see action handling in all 3 flavors search/app/pinboard, can we converge these to be in the single place ?

Also, lets throw an error when the user uses both `visibleActions` and `hiddenActions`

2021-09-07 20:31 UTC, ashubham requested changes
PTAL at the comment

2021-09-13 08:27 UTC, kailash-choudhary-thoughtspot commented on src/embed/search.ts
> +        }
since now we support Actions for each embed flavour, shall we add it in Base Class.

2021-09-15 18:11 UTC, ashubham approved these changes

2021-09-15 18:12 UTC, ashubham commented on src/embed/ts-embed.ts
> +     */
Can we put a tag like "Available since: 1.5.0"

2021-09-16 13:40 UTC, merged