SCAL-101403: Added firefox specific css
thoughtspot/visual-embed-sdk pull request #451
Opened 2021-11-17 07:53 UTC by aditya-kumar44

2021-11-17 09:10 UTC, kailash-choudhary-thoughtspot commented on docs/src/assets/styles/index.scss
> +
why its happening for Mozilla only?

2021-11-17 09:10 UTC, kailash-choudhary-thoughtspot commented on docs/src/assets/styles/index.scss
> +
can you add comment why its specific to mozilla

2021-11-17 09:18 UTC, aditya-kumar44 commented on docs/src/assets/styles/index.scss
> +
This is very common problem. CSS behave differently on different browsers. 
To fix we use below:

Mozilla uses -moz-
Chrome/Opera/Safari use -webkit-
Microsoft uses -ms-

2021-11-17 14:34 UTC, akashmohapatra requested changes

2021-11-17 14:34 UTC, akashmohapatra commented on docs/src/assets/styles/index.scss
> +
Please double check the calculation of the left nav width as that seems to be different across both the browsers

2021-11-18 07:37 UTC, aditya-kumar44 commented on docs/src/assets/styles/index.scss
> +
Problem seems to be from this line of code:
const { width, ref } = useResizeDetector();
In chorme it is giving width 1361 and in firefox it is giving 1054.
Due to this there is inconsistency between both the browsers.
Also, 
const [leftNavWidth, setLeftNavWidth] = useState(
        width > MAX_TABLET_RESOLUTION
            ? LEFT_NAV_WIDTH_DESKTOP
            : LEFT_NAV_WIDTH_TABLET,
    );

Here, leftNavWidth is never taking initial value. I checked after removing initial value, still it is taking 304 and 309. It is not being set from anywhere.

2021-11-19 13:03 UTC, closed without merging

2021-11-19 13:03 UTC, aditya-kumar44 commented
Closing