Updated currentRoute & remove hidden for routechange
thoughtspot/visual-embed-sdk pull request #460
Opened 2021-11-23 15:15 UTC by gaurav-thoughtspot

https://thoughtspot.atlassian.net/browse/SCAL-101584

2021-12-03 22:30 UTC, ashubham approved these changes

2021-12-03 22:30 UTC, ashubham commented on src/embed/liveboard.ts
> +        if (!data.data.currentPath.startsWith('/embed/viz/')) {
Question here. So we do not want to set the height when the route is not a pinboard ? When will this happen ? And the function being named `handleRouteChangeFullHeightLiveboard` feels a bit convoluted.

2021-12-03 22:31 UTC, ashubham requested changes
approved by mistake. Please see comment on PR

2021-12-06 06:49 UTC, kailash-choudhary-thoughtspot commented on src/embed/liveboard.ts
> +        if (!data.data.currentPath.startsWith('/embed/viz/')) {
here we are setting the default height. If we move away from the embed-pinboard route we set the height of Iframe as the default height provided by user.

2021-12-06 20:18 UTC, ashubham commented on src/embed/liveboard.ts
> +        if (!data.data.currentPath.startsWith('/embed/viz/')) {
I see. This function seems to handle the case when the route is not "/embed/viz" but is named "handleRouteChangeForFullHeightLiveboard" isnt that convoluted ?

2021-12-07 04:19 UTC, ashubham approved these changes

2021-12-07 04:19 UTC, merged