Added New Embed event
thoughtspot/visual-embed-sdk pull request #578
Opened 2022-03-25 09:53 UTC by gaurav-thoughtspot

2022-03-28 01:44 UTC, ShashiSubramanya reviewed
The description text for some events requires minor edits. Please check the comments.

2022-03-28 01:44 UTC, ShashiSubramanya commented on src/types.ts
> +     * Emitted when ShowUnderlyingData trigger in answer on the app
Emitted when a user clicks Show underlying data on an answer.

2022-03-28 01:44 UTC, ShashiSubramanya commented on src/types.ts
> +     * Emitted when Switching between chart and table in answer on the app
Does this make sense?
"Emitted when an answer is switched to a chart or table view."

2022-03-28 01:44 UTC, ShashiSubramanya commented on src/types.ts
> +     * Emitted when Download PDF for answer in the app
Does this apply only to answers? If yes, let's change the text to "Emitted when the Download as PDF action is triggered on an answer"

2022-03-28 01:44 UTC, ShashiSubramanya commented on src/types.ts
> +     * Emitted when Download CSV for answer in the app
Emitted when the Download as CSV action is triggered on an answer

2022-03-28 01:44 UTC, ShashiSubramanya commented on src/types.ts
> +     * Emitted when Download XLSX for answer in the app
Emitted when the Download as XLSX action is triggered on an answer

2022-03-28 01:44 UTC, ShashiSubramanya commented on src/types.ts
> +     * Emitted when answer is shared to specifc email on the app
Does this apply only to answers? If not, could we change the text to "Emitted when a user shares an object with another user or group"?

2022-03-30 22:31 UTC, ashubham requested changes
Lets write unit tests for this.

2022-03-30 22:31 UTC, ashubham commented on src/embed/ts-embed.ts
> +        }
Might be good to align with the web standard of `addEventListener` here. https://developer.mozilla.org/en-US/docs/Web/API/EventTarget/addEventListener 

Basically the interface could be:
```js
embed.on('eventName', callback, { start: true }); // The default value of start is false.
```

When `start` is true it gets called in the start phase, else it gets called in the end phase.

2022-03-30 22:31 UTC, ashubham commented on src/types.ts
> +type messageCallbackObj = {
capital `M`

2022-03-30 22:31 UTC, ashubham commented on src/types.ts
> +    /**
We already have these defined in the Action enum, we should perhaps use the value here instead of redefining.

2022-03-31 06:53 UTC, ashubham requested changes
Please add unit tests

2022-03-31 06:53 UTC, ashubham commented on src/embed/ts-embed.ts
> +        callbacks.forEach((callbackObj) => {
Can you please explain in a comment here what the if condition represents.

2022-03-31 06:55 UTC, ashubham commented on src/types.ts
> +export type MessageOptions = {
Lets add Documentation / ts-docs here

2022-03-31 09:11 UTC, ashubham commented on src/embed/ts-embed.ts
> +        }
There is nothing called end: true .. There is only one param start .. and that can either be false or true. false means it will be invoked at the end.

If you want both start and end handlers, you should have 2 event handlers one with start: true and one with start: false.

This is exactly similar to addEventListener with capture flag.

2022-04-01 22:16 UTC, ashubham requested changes

2022-04-01 22:16 UTC, ashubham commented on src/embed/ts-embed.spec.ts
> +    describe('Called Embed event status for start and end', () => {
We need 2 more test cases:
- When handler is `start: true` and event is emitted with `status: end`. The handler should not be called.
- The opposite of above.

2022-04-01 22:16 UTC, ashubham commented on src/types.ts
> + * MessagePayload: Embed event payload: message type, data and status (start/end)
The fields are documented inside the interface, look at the other interfaces in this file.

2022-04-08 11:34 UTC, akashmohapatra commented on src/types.ts
> + * MessagePayload: Embed event payload: message type, data and status (start/end)
Please add comments on the interface attributes directly

2022-04-08 13:52 UTC, akashmohapatra approved these changes

2022-04-08 13:56 UTC, merged