[SCAL-120655]: Implemented Beta Warning for users on unsupported versions of SearchE…
thoughtspot/visual-embed-sdk pull request #665
Opened 2022-06-07 09:20 UTC by gaurav-thoughtspot

Fixed SCAL-120655

2022-06-07 09:38 UTC, jbhanu-thoughtspot requested changes

2022-06-07 09:38 UTC, jbhanu-thoughtspot commented on src/auth.ts
> +    'Search Embed is in Beta in this release.';
Maintain this text in `errors.ts` instead

2022-06-07 09:38 UTC, jbhanu-thoughtspot commented on src/auth.ts
> +        checkReleaseVersionInBeta(sessionInfoResp.releaseVersion);
Store the releaseVersion in a variable on this file, similar to `sessionInfo`. And move the logic to checkReleaseVersionInBeta and calling alert from SearchEmbed render method.

2022-06-10 05:08 UTC, jbhanu-thoughtspot requested changes

2022-06-10 05:08 UTC, jbhanu-thoughtspot commented on src/utils/checkReleaseVersionBeta.ts
> +export const checkReleaseVersionInBeta = (): boolean => {
Change this function instead to accept releaseVersion and suppresBetaWarning flag as parameters. So that removes the dependency on the base.ts and auth.ts from the util file. Then move back this method into the util.ts.

```
export const checkReleaseVersionInBeta = (releaseVersion: string, suppressBetaWarning: boolean): boolean => {
    const splittedReleaseVersion = releaseVersion.split('.');
    const isBetaVersion =
        Number(splittedReleaseVersion[0]) >= 8 &&
        Number(splittedReleaseVersion[1]) >= 4;
    return !suppressBetaWarning && isBetaVersion;
}
```

2022-06-13 12:54 UTC, jbhanu-thoughtspot submitted a review, later dismissed

2022-06-13 12:54 UTC, jbhanu-thoughtspot commented on src/utils.ts
> +    const splittedReleaseVersion = releaseVersion.split('.');
It seems we also need to check if the cluster is a software, so can you also check if this ends with `.sw`?

2022-06-16 13:33 UTC, akashmohapatra approved these changes

2022-06-16 14:15 UTC, akashmohapatra approved these changes

2022-06-17 11:34 UTC, merged