Added new post method for token API
thoughtspot/visual-embed-sdk pull request #714
Opened 2022-08-10 08:07 UTC by gaurav-thoughtspot

https://thoughtspot.atlassian.net/browse/SCAL-125593

2022-08-12 18:59 UTC, ashubham requested changes

2022-08-12 18:59 UTC, ashubham commented on src/auth.ts
> +        }
We need to write a unit test which asserts that GET is called if POST fails.

2022-08-26 09:42 UTC, jbhanu-thoughtspot approved these changes

2022-08-26 16:50 UTC, ashubham approved these changes

2022-08-26 16:50 UTC, merged