SCAL-130835 Style Customization Metrics for which framework is most used
thoughtspot/visual-embed-sdk pull request #749
Opened 2022-10-10 14:54 UTC by demon12321

2022-10-11 05:28 UTC, ashubham requested changes

2022-10-11 05:28 UTC, ashubham commented on src/embed/base.ts
> +
Couldn't we just add these variables to the `init` event above ? Instead of introducing a new event

2022-10-11 05:33 UTC, demon12321 commented on src/embed/base.ts
> +
Bhanu told me to create a new event maybe because we need to add more eventprops in this event.

2022-10-11 06:19 UTC, ashubham requested changes

2022-10-11 06:19 UTC, ashubham commented on src/embed/base.ts
> +        usedSheet: embedConfig.customisations?.style?.customCSSUrl != null,
usedCustomizationSheetUrl

2022-10-11 06:19 UTC, ashubham commented on src/embed/base.ts
> +        usedVariables:
usedCustomizationVariables

2022-10-11 06:19 UTC, ashubham commented on src/embed/base.ts
> +        usedRules:
usedCustomizationRules

2022-10-12 04:49 UTC, ashubham approved these changes

2022-10-12 04:49 UTC, merged