[SCAL-78871]: Move Embed SDK render params to constructor Params
thoughtspot/visual-embed-sdk pull request #81
Opened 2021-03-09 19:26 UTC by sumit-thoughtspot

2021-03-09 20:07 UTC, ashubham requested changes

2021-03-10 11:58 UTC, ayonghosh commented on src/embed/pinboard.ts
> +        }
Move this validation to the render function as we will trigger an "error" event

2021-03-10 11:59 UTC, ayonghosh commented on src/embed/app.spec.ts
> +        } as AppViewConfig);
What happens if we don't do this type casting?

2021-03-11 08:06 UTC, sumit-thoughtspot commented on src/embed/pinboard.ts
> +        }
done

2021-03-11 08:09 UTC, sumit-thoughtspot commented on src/embed/app.spec.ts
> +        } as AppViewConfig);
This will show an error.

AppEmbed and PinboardEmbed use V1Embed constructor method for initialization.

V1Embed constructor takes viewConfig of type ViewConfig.

So that is why we need to typecast the arguements.

2021-03-12 11:28 UTC, ayonghosh approved these changes

2021-03-12 11:41 UTC, merged