Add missing enum Rename
thoughtspot/visual-embed-sdk pull request #870
Opened 2023-04-24 09:47 UTC by adityamittal3107

2023-04-24 09:58 UTC, abdullasulaiman requested changes

2023-04-24 09:58 UTC, abdullasulaiman commented on src/types.ts
> +    Rename = 'renameModalTitleDescription',
Can we name it more descriptive enum. Rename is very general as it TitleDescription Rename right ?

2023-04-27 09:59 UTC, Nirmay15 approved these changes

2023-04-27 10:02 UTC, abdullasulaiman approved these changes
Looks good.

2023-04-27 10:03 UTC, merged