SCAL-157042 : Update reload function
thoughtspot/visual-embed-sdk pull request #880
Opened 2023-05-19 04:28 UTC by Nirmay15

2023-05-22 10:35 UTC, girish-thoughtspot approved these changes

2023-05-22 16:28 UTC, abdullasulaiman requested changes
Please see the comment

2023-05-22 16:28 UTC, abdullasulaiman commented on src/utils/processTrigger.ts
> +export const reload = (iFrame: HTMLIFrameElement) => {
export const reload = (iFrame: HTMLIFrameElement) => {
    const src = iFrame.src;
    iFrame.src = '';
    requestAnimationFrame(() => {
        iFrame.src = src;
    });
};
Can you please try with requestAnimationFrame and see if it works ?

2023-05-23 07:23 UTC, abdullasulaiman approved these changes
lgtm

2023-05-23 07:28 UTC, Nirmay15 commented on src/utils/processTrigger.ts
> +export const reload = (iFrame: HTMLIFrameElement) => {
It is not reloading the whole frame, it is working as internal navigation

2023-05-23 07:28 UTC, merged