Solved Stuttering issue
thoughtspot/visual-embed-sdk pull request #94
Opened 2021-03-16 12:28 UTC by aayushgupta6

2021-03-17 12:47 UTC, ayonghosh approved these changes

2021-03-18 06:01 UTC, pankajp-ts requested changes

2021-03-18 06:01 UTC, pankajp-ts commented on docs/src/pages/index.tsx
> +
remove this new line `(line 153)`

2021-03-18 06:01 UTC, pankajp-ts commented on docs/src/pages/index.tsx
> +                        <Suspense fallback={<div> </div>}>
do we need space between tag `<div> </div>` if not please remove it.

2021-03-18 06:12 UTC, aayushgupta6 commented on docs/src/pages/index.tsx
> +                        <Suspense fallback={<div> </div>}>
No, I'll remove it

2021-03-18 06:13 UTC, aayushgupta6 commented on docs/src/pages/index.tsx
> +
ok

2021-03-18 06:13 UTC, aayushgupta6 commented on docs/src/pages/index.tsx
> +        <>
ok

2021-03-18 06:13 UTC, aayushgupta6 commented on docs/src/pages/index.tsx
> +import React, { useState, useEffect,Suspense,lazy } from 'react';
ok

2021-03-18 06:58 UTC, pankajp-ts approved these changes
LGTM 👍

2021-03-18 07:01 UTC, merged