PreRender
thoughtspot/visual-embed-sdk pull request #979
Opened 2023-09-22 11:55 UTC by sastaachar

2023-10-04 07:42 UTC, pushkar100 requested changes
Behaviour looks good. Need quite a bit of refactoring though

2023-10-04 07:42 UTC, pushkar100 commented on src/embed/ts-embed.ts
> +        child.id = preRenderIds.child;
Seems like a bug. Is this `child` element being implicitly created?

2023-10-04 07:42 UTC, pushkar100 commented on src/embed/ts-embed.ts
> +        setStyleProperties(preRenderShield, { position: 'absolute', width: '100%', height: '100%' });
Abstract away this frequently used logic.
```suggestion
const createUnqiueDivWithStyle = (id, styles) => {
    const div = document.createElement('div');
    div.setAttribute('id', id);
    setStyleProperties(div, styles);
    return div;
};

this.preRenderWrapper = createUnqiueDivWithStyle(preRenderIds.wrapper, { position: 'absolute', width: '100vw', height: '100vh' });
this.preRenderWrapper = createUnqiueDivWithStyle(preRenderIds.shield, { position: 'absolute', width: '100%', height: '100%' });
```

2023-10-04 07:42 UTC, pushkar100 commented on src/embed/ts-embed.ts
> +    public preRender(showPreRenderByDefault = false): TsEmbed {
Feel that renaming `showPreRenderByDefault ` to something like `renderImmediately` conveys the option better

2023-10-04 07:42 UTC, pushkar100 commented on src/embed/ts-embed.ts
> +            console.log('No preRender found, not hiding ');
nit:- remove the log

2023-10-04 07:42 UTC, pushkar100 commented on src/embed/ts-embed.ts
> +            && !!this.preRenderChild;
nit:-
```suggestion
        return Boolean(this.preRenderWrapper && this.preRenderShield
            && this.preRenderChild);
```

2023-10-04 07:42 UTC, pushkar100 commented on src/embed/ts-embed.ts
> +        this.preRenderWrapper = this.preRenderWrapper
Why will we need to re-read the wrapper/shield/child from the DOM once it has been assigned to the class property?

2023-10-04 07:42 UTC, pushkar100 commented on src/embed/ts-embed.ts
>              return getAuthPromise()
Branching into a different logic based on multiple `if`s on `this.isPreRendered` will lead to bloated, convoluted code.
Let us try to use a strategy pattern to split the logic between justr render and prerender. Ex:
```javascript
const renderStrategy = { success: () => { ... }, error: => { ... }};
const preRenderStrategy = { success: () => { ... }, error: => { ... }};
const setAuthPromiseStrategy = (isPreRendered) => {
    return isPreRendered ? preRenderStrategy : renderStrategy;
}
const authPromiseCallbacks = setAuthPromiseStrategy(this.isPreRendered);

return getAuthPromise(authPromiseCallbacks.success)?.then(authPromiseCallbacks.error);
```

2023-10-04 08:37 UTC, sastaachar commented on src/utils.ts
> +    element: HTMLElement,
There is no if here , i think you may have commented wrong line

2023-10-04 09:46 UTC, pushkar100 commented on src/utils.ts
> +    element: HTMLElement,
Refer `if (!element || !styleProperties) return;`

2023-10-04 10:06 UTC, sastaachar commented on src/embed/ts-embed.ts
> +        child.id = preRenderIds.child;
no its passed as parameter for the function , its the child that we are going to render

2023-10-04 10:07 UTC, sastaachar commented on src/embed/ts-embed.ts
> +    public preRender(showPreRenderByDefault = false): TsEmbed {
we render immediately all the time, the difference here is that we hide it by default , thats y i had named it show by default


render -> hide (normal flow)
render -> show (showPreRenderByDefault flow)

2023-10-04 10:08 UTC, sastaachar commented on src/embed/ts-embed.ts
> +            console.log('No preRender found, not hiding ');
yes i will be removing all the logs and cleaning , PS : it does not give any lint error (it should)

2023-10-04 10:09 UTC, sastaachar commented on src/embed/ts-embed.ts
> +        this.preRenderWrapper = this.preRenderWrapper
this is for the case where another object tries to connect to our preRender

2023-10-04 10:12 UTC, sastaachar commented on src/embed/ts-embed.ts
>              return getAuthPromise()
90% of the code is similar for both strategy , I'll move this logic to another function which will make it more clear as well and branch their based on the strategy

2023-10-05 05:56 UTC, pushkar100 commented on src/embed/ts-embed.ts
> +    public preRender(showPreRenderByDefault = false): TsEmbed {
`showImmediately` makes sense to me. The `bydefault` is what is confusing

2023-10-17 09:40 UTC, pushkar100 approved these changes
LGTM. Let's organise a bug hunt

2023-10-17 09:41 UTC, pushkar100 commented
@Nirmay15 Can you please review this too?

2023-10-27 17:05 UTC, ashubham commented on src/react/index.tsx
> +    * embed.showPreRender();
Lets have a React example here.

2023-10-27 17:05 UTC, ashubham commented on src/types.ts
> +    trackPreRenderSize?: boolean;
Lets always have default values as `false`. Change this to `doNotTrackPrerenderSize`

2023-10-27 17:05 UTC, ashubham commented on src/react/index.tsx
> +    isPreRenderedComponent = false,
Lets put comments to what this does.

Also, I see multiple f else conditions inside, is it possible to structure this to be more composed ?

2023-10-29 08:11 UTC, merged